language: java

jdk:
  - oraclejdk8

install: ./gradlew clean assemble

script:
  - ./gradlew clean :replayable-interface:build :replayable-interface-compiler:build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "QfIJR0+sYXnkXDcU3fgm1l9+ZwP/SDnmCnOrAFjZaA0b8HAmbEQ
    +nG9hKsmX2uF0GeFjeolbjJ8trvr5xCAJ6ko6b9JsSN02j+koYQ0/7i+F6VqfHtTm31UMykWqBhFGX+O9tRg7d7WFHUoVorWade9o2TnxUehziSXx+356FJSvWNdC9dDRrNLn8GbC/IRCZqFzibRMUwttuF8D0X1oIifPYfjt23T0LEffUUvqLZncUQVaI826ix9vOC+0Ni5plEXwWyVVTWqTS5V2rY2LfPqBuucIvbw7kRkVqWUu1YRB6b4RklUQZFba3qk4ptNX9YOvxGPl9HiQgMpSglrCkHudjIersP5AT7bbtsqCd/favw+bVlRL9A8svLOYgg4I76ma2ATZdFPcPdQjla+i+xRDN21OVAabcSwxEh61ArpkcxixGoIUrgxTz1w/SGgv1bIjaPi3joDL79guBFiQPq4+d/urc3EBfiKUzQtKEPaOsQufV/MUgQLfajXuqsS6ugkQNg1DssgEgzLSUH7+4zPvbZZUjpVfFo4rCvnxwpWPIjcbPVWCiak47f02BQ7ts7HdN0K2YIfhkLNu8z/coV6yqWXtrJGTAXNf8TGJLMg9KNWDaT2+2jfaqqgVQltFJ3KBTkthsxB0Thks2+RwigwlPoU5lCKB++ekUh5t6Js="
    - secure: "qg2ZN7d2BSAcnoN3pUQ8pE+QT7fIuV1sT1It4vs7Xg4Hhdl4qam4GgpKHCCDOZM4l0IqOpASq9AwbxDFxQjvGOoip47UYo+v3HBIv7FsPrVWDI/w92G8jhUmWcVcxh5pzLcclqQE1umkslHN3S78+UY3YhO48jC0J8EzXC+b7Hr3mc8rp59593spdlzD/zf5IerUypJPFD2yEUUkqBhEaPCVpw1BRHiF3Jjm8dEgwrkWCdVe+WA/ZgoEAM5Z84WiS0XDlYJ4EfqfvgZlraX+nui+ywZwHGUhkoRbheCVIgJ9KHC0iVVMhIwUj+IkXCJloIpwnY5EVjUJ5ya95fHMMqCCmfDEd8wcy9eki50ceOecUg+0vsMaefqweH6EOnHAdYeLcixr1ilYMSI97hjzBrrhn73PVB2FVhKO7bjkplvgyia4y+YqbazP/dE0IHJ3dmPtLO8KpTQM2dv3i1U+j6QG6oNQUoVF4h1wa/LjItStOm2/p21UIQjgE6zt6ztKo/m20CL/vSC/zgoq/mp+CZCe/JOC8NdyXFg/8G0M+ySrKJJccya3rz1g8svV7jQj6NIIu4M7z2Hyl19yK1MD3jguvANrVEJDo1RRx9HWvvSvyJNDvclOeyIKzShmrf75hz5ZIk33ej53X/+BmJ5VZqjfNTAkOTm9+aP+vhzyMCk="

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle