language: java

jdk:
  - oraclejdk8

install: ./gradlew clean assemble

script:
  - ./gradlew clean :replayable-interface:build :replayable-interface-compiler:build

#after_success:
#  - .buildscript/deploy_snapshot.sh

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle